### PR TITLE
Feature/host player list

### PR DESCRIPTION
**Pull request by Alexamakans**
Still not done, but want to get it up as a PR so "others" :) can have an easier look and chime in on the changes.

- Added new scene `LobbyScene`
- Moved join code display to lobby scene.
- Added transition from `HostOrJoinScene` to lobby scene on connect.

- Added new scripts (skipping explanation for some as they are fairly self explanatory)
  - `PlayerManager.cs` -> Has synchronized list of players between clients.
  - `PlayerList.cs` -> Listens for changes in that list, and updates entries when changed.
  - Skipped: `JoinCodeScript.cs`, `JoinCodeSetter.cs`, `Player.cs`, `LobbyScript.cs`

### CODE REVIEW

**Comment by jilleJr** [comment]
> Still not done, but want to get it up as a PR so "others" :) can have an easier look and chime in on the changes.

Just mark it as "ready for review" when you want the review :P No damage in having it open but unfinished, I will just most probably "request changes" in either case

**Review by applejag — APPROVED** [review]
Instead of leaving a lot of suggestions, I pushed changes directly.

Trying out something new. As reviewing Unity scenes and prefabs isn't really realistic to do via GitHub.com

**Comment by jilleJr** [comment]
Gotta say it's really cool that this even works. After all debugging and research of how it works, the actual code we have to add is so minimal. It truly simplifies networking by a landslide

**Comment by jilleJr** [comment]
I'm merging this even though you haven't responded to my review comments yet. If you don't agree, you can always lynch me later.

**Comment by Alexamakans** [comment]
> I'm merging this even though you haven't responded to my review comments yet. If you don't agree, you can always lynch me later.

Oop sorry yup 👍

**Pull request merged**
